"""empty message

Revision ID: 271af18dd3f8
Revises: a5cffa318ac2
Create Date: 2025-08-25 23:42:59.096252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271af18dd3f8'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])

    # ### end Alembic commands ###
